### ISSUE TITLE
Secure datalink metaissue

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#2189]
This issue is to track progress of merging individual part of the secure datalink.

To be merged:
- [x] update libopencm3 to the latest version
- [x] add random number generator driver (for STM32)
- [x] add HACL* as a submodule, and hacl-c as a module
- [x] add installation scripts for HACL* library and hacl-c module
- [x] update pprzlink to include secure_pprz_transport
- [x] add secure_transport module with key exchange algorithm
- [x] add key generator (Rust/Python)
- [x] add secure Datalink for GCS (Rust/Python)
- [x] add documentation with examples 

Progress on the secure link itself:

- [x] symmetric encryption implemented and tested
- [x] key generator with HACL* library implemented
- [x] implement key exchange algorithm
- [x] update Datalink for GCS to handle secure link
- [x] test(s)

Hoping to get it integrated into 5.14 release.

**Comment by podhrmic** [comment]
Closed with #2205 #2235 #2245
