### ISSUE TITLE
Rotwing in master

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#3093]
minimum viable 3B:
----------
- [x] UAVCAN airspeed #3074
- [x] hanging rm3100 #3080
- [x] multi imu sending #3084
- [x] mavlink camera control #3085
- [x] moving target gains in airframe #3086
- [x] cube+ #3087
- [x] cube gyro timing fix #3099
- [x] extra preflight checks #3159
- [x] sys_ident update #3075
- [x] uavcan esc temp #3088
- [x] actuator ID #3089
- [x] uavcan actuator telemetry #3129
- [x] multiple airspeed #3094
- [x] airspeed data not equal to state airspeed #3098
- [x] 3098 fix #3114
- [x] ground detect #3077
- [x] ground detect fix #3156
- [x] wind EKF message https://github.com/paparazzi/pprzlink/pull/174
- [x] wind speed EKF #3078
- [x] negative airspeed when tailwind #3126
- [x] airborne disarm #3081
- [x] not kill with thrust 0 #3163
- [x] full INDI message #3101
- [x] max nav_hybrid accel #3102
- [x] set NAV_HYBRID_MAX_DECELERATION to 0.5
- [x] notch filtering #3128
- [x] stabilization_indi feed-forward rates #3068
- [x] 3068 fix #3113
- [x] 2nd order rate filters #3104
- [x] 3D vector from guidance to stabilization #3116
- [x] LIFT_D Abi #3117
- [x] WLS as module #3115
- [x] NaN WLS fix #3120
- [x] Debug vectors message https://github.com/paparazzi/pprzlink/pull/179
- [x] quadplane stabilization #3121
- [x] quadplane guidance #3122
- [x] rotwing ctrl_eff #3124
- [x] 25kg msg fix #3144
- [x] extra ADC for 25 #3134
- [x] RW25 #3133
- [x] rotwing ctrl_eff 3B not compatible with 25kg #3158
- [x] rotwing status message https://github.com/paparazzi/pprzlink/pull/178
- [x] turn radius https://github.com/paparazzi/paparazzi/issues/3069
- [x] simulator #3125
- [x] update visualizer #3119
- [x] Filter IMU #3164
- [x] Debug guidance #3157
- [x] Cleanup Tailsitter versus Quadplane #3161
- [x] preflight checklist #2951
- [x] AutoRCCommands Overwritten by Stabilization #3162
- [x] 3b wing controller rotwing #3143
- [x] state_machine #3169
- [x] 3b automation #3172
- [x] final airframe #3176

minimum viable 25:
----------

- [x] wing controller CAN #3177

important:
-----------

- [x] NPS fix: #3175
- [x] Flightplans do no hardcoded booleans but requests: #3201
- [x] Preflight on actuator deflections: #3202
- [x] simulator with flaps, highspeed telemetry #3173
- [x] simulator no IMU when IMU_ACCEL #3135
- [x] MAVLink camera control needs AP to identify as ARDUPILOT #3178

extras:
------
- [x] Cube with INPUTS #3131
- [x] windtunnel #3079
- [x] INS filters off by default #3174

**Comment by tmldeponti** [comment]
1. Add rotorcraft "type" instead of using guidance_indi_hybrid quad plane or tailsitter. Like that also other people that do not use guidance indi hybrid can use your code. 
2. Specify dependency of wing_rotation_controller on rotwing_state. 
3. In rotwing state remove dependecies on stabilizatuion_indi and guidance_indi_hybrid. This way other people that do not use these modules can still use the rotwing_state. For example the function "guidance_indi_hybrid_set_wls_settings" could be included in guidance_indi_hybrid.c

**Comment by dewagter** [comment]
Completed
