### ISSUE TITLE
Merge rowing_dev again

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#3362]
# Check new updates in master (but not in rotwing_dev)
Not often tested and could possibly interfere
 - [x] #3320 WLS
 - [x] #3334 Rot-Wing State 
 - [x] #3333 Oneloop
 - [x] #3335 nav hybrid updates
 - [x] #3381 oneloop update
 - [x] #3382 rotwing demo

# Missing in Master
 - [x] #3357 Remove useless defines
 - [x] #3358 Faulhaber update
 - [x] #3359 Fuel-cell monitoring 
 - [x] |-> (needs https://github.com/paparazzi/pprzlink/pull/195) and Needs UAVCAN message pull-request
 - [x] #3360 Airspeed filtering
 - [x] #3361 Power over UAVcan monitor
 - [x]  |-> (needs https://github.com/paparazzi/pprzlink/pull/193) 
 - [x] #3363 Extra Uarts 
 - [x] #3364 Init
 - [x] #3365 Rename ground sensors
 - [x] #3366 Rename all rotwing stuff consistently
 - [x] #3367 Uavcan actuator update
 - [x] #3377 + fix
 - [x] #3368 preflight check fix
 - [x] #3369 Mavlink updates
 - [x] #3373 remove WP automation
 - [x] #3375 update simulator
 - [ ] #3383 simulate broken motors
 - [x] Make common airframe files
 - [x] Rewrite of the state machine
 - [x] #3374 - Add min_airspeed and max_airspeed, new state-machine etc in hybrid_guidance
 - [x]   |->needs: https://github.com/paparazzi/pprzlink/pull/194
 - [ ] #3376 - Use COMMANDS
 - [ ] #3386 - update MAX_SPEEDS
 - [x] https://github.com/paparazzi/pprzlink/pull/197 - python tools broken
 - [x] #3388 - final tweaks
 - [x] #3391 - rebase rotwing_dev
