### ISSUE TITLE
peripheral and imu driver refactor/cleanup

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#345]
Peripherals like sensors should have their own driver which can then be reused in the different IMU drivers.
Also the peripheral drivers should not use any global variables and instead take a pointer to the struct containing all neccessary information as a parameter. This makes it possible to run multiple of the same peripherals at a time (and is cleaner anyway...).

List of subtasks (not complete yet):
- [x] hmc58xx magnetometer refactoring #105
- [ ] hmc58xx data ready interrupt handling
- [x] itg3200 gyro (also imu3000) refactoring
- [ ] itg3200 data ready interrupt handling
- [x] l3g4200 i2c gyro
- [x] adxl345 i2c peripheral
- [x] adxl345 spi peripheral
- [ ] adxl345 data ready interrupt handling
- [x] mpu60xx peripheral #190 #450
- [ ] max1168 adc peripheral
- [ ] ads1114 adc peripheral
- [ ] ms2100 magnetometer peripheral
- [ ] ami601 magnetometer peripheral
- [x] ms5611 barometer peripheral #515
- [x] bmp085 barometer peripheral #515
- [x] mpl3115 barometer/altimeter
- [x] imu_navgo driver
- [x] imu_umarim driver
- [x] imu_aspirin (via spi) refactoring (only polling, no interrupt handling)
  should also work on lpc now
- [x] imu aspirin (i2c)
- [x] imu_aspirin2 refactoring #450
- [x] imu_ppzuav refactoring #192

**Comment by gautierhattenberger** [comment]
- max1168 adc peripheral (only for obsolete booz imu driver)
- ads1114 adc peripheral (only for some obsolete Enac baro boards)
- ms2100 magnetometer peripheral (only for obsolete booz imu driver)
- ami601 magnetometer peripheral (only for some version of obsolete booz imu)
- hmc58xx data ready interrupt handling (is it actually used? not all boards have the pin routed anyway)
- itg3200 data ready interrupt handling (same thing + mostly for obsolete boards)

It looks like it is not worth the effort of converting the old drivers, and concerning the interrupt, the real issue is that we actually miss a proper general API for external triggers.

I suggest to close the issue.
